# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftransport.proto\x12\x08mercatia\"\x1d\n\rEconomyReport\x12\x0c\n\x04name\x18\x01 \x01(\t\"-\n\x0c\x43onfirmation\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2S\n\tTransport\x12\x46\n\x11SendEconomyReport\x12\x17.mercatia.EconomyReport\x1a\x16.mercatia.Confirmation\"\x00\x42!\n\x16org.mercatia.transportB\x05ProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transport_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026org.mercatia.transportB\005ProtoP\001'
  _globals['_ECONOMYREPORT']._serialized_start=29
  _globals['_ECONOMYREPORT']._serialized_end=58
  _globals['_CONFIRMATION']._serialized_start=60
  _globals['_CONFIRMATION']._serialized_end=105
  _globals['_TRANSPORT']._serialized_start=107
  _globals['_TRANSPORT']._serialized_end=190
# @@protoc_insertion_point(module_scope)
